### ISSUE TITLE
Accuracy question, master slave and slave-slave

### ISSUE THREAD

**Issue by iliesaya** [RIAPS/riaps-timesync#15]
Hi, 

I have 3 beagleBone Black running the default RIAPS image, and I configured 1 to be Master and 2 to be Slave :

On Master:
`riaps@bbb-9c4a:~/git/riaps-timesync/python$ timesyncctl status
INFO: Everything looks fine for role: master
`

On the 2 slave :
`riaps@bbb-e59a:~/git/riaps-timesync/python$ timesyncctl status
INFO: Everything looks fine for role: slave
`

I am running the simple python example (riaps-timesync/python/test_timesync.py) to print the time each second , and I am reading your article "Time Synchronization Services for Low-Cost Fog Computing Applications".

ptp4l is running on all the beaglebone , here is the log of /var/log/ptp4l.log

on Master:
`riaps@bbb-9c4a:~/git/riaps-timesync/python$ cat /var/log/ptp4l.log
Aug 21 08:57:07 bbb-9c4a ptp4l: [427.733] selected /dev/ptp0 as PTP clock
Aug 21 08:57:07 bbb-9c4a ptp4l: [427.817] port 1: INITIALIZING to LISTENING on INITIALIZE
Aug 21 08:57:07 bbb-9c4a ptp4l: [427.830] port 0: INITIALIZING to LISTENING on INITIALIZE
Aug 21 08:57:07 bbb-9c4a ptp4l: [427.831] port 1: link up
Aug 21 08:57:08 bbb-9c4a ptp4l: [428.122] selected /dev/ptp0 as PTP clock
Aug 21 08:57:08 bbb-9c4a ptp4l: [428.221] port 1: INITIALIZING to LISTENING on INITIALIZE
Aug 21 08:57:08 bbb-9c4a ptp4l: [428.224] port 0: INITIALIZING to LISTENING on INITIALIZE
Aug 21 08:57:08 bbb-9c4a ptp4l: [428.228] port 1: link up
Aug 21 08:57:15 bbb-9c4a ptp4l: [435.518] port 1: LISTENING to MASTER on ANNOUNCE_RECEIPT_TIMEOUT_EXPIRES
Aug 21 08:57:15 bbb-9c4a ptp4l: [435.518] selected best master clock 304511.fffe.749c4a
Aug 21 08:57:15 bbb-9c4a ptp4l: [435.518] assuming the grand master role
`

On slave:
`
Aug 21 14:34:55 bbb-dd03 ptp4l: [12843.966] master offset        149 s2 freq  +37944 path delay     10894
Aug 21 14:34:56 bbb-dd03 ptp4l: [12844.966] master offset         87 s2 freq  +37926 path delay     10902
Aug 21 14:34:57 bbb-dd03 ptp4l: [12845.967] master offset       -174 s2 freq  +37692 path delay     10902
Aug 21 14:34:58 bbb-dd03 ptp4l: [12846.967] master offset         83 s2 freq  +37896 path delay     10902
Aug 21 14:34:59 bbb-dd03 ptp4l: [12847.967] master offset        117 s2 freq  +37955 path delay     10894
Aug 21 14:35:00 bbb-dd03 ptp4l: [12848.967] master offset        -53 s2 freq  +37820 path delay     10902
Aug 21 14:35:01 bbb-dd03 ptp4l: [12849.967] master offset        -46 s2 freq  +37811 path delay     10902
Aug 21 14:35:02 bbb-dd03 ptp4l: [12850.968] master offset          0 s2 freq  +37844 path delay     10894
Aug 21 14:35:03 bbb-dd03 ptp4l: [12851.968] master offset        -43 s2 freq  +37801 path delay     10888
Aug 21 14:35:04 bbb-dd03 ptp4l: [12852.968] master offset         97 s2 freq  +37928 path delay     10878
Aug 21 14:35:05 bbb-dd03 ptp4l: [12853.968] master offset         37 s2 freq  +37897 path delay     10876
Aug 21 14:35:06 bbb-dd03 ptp4l: [12854.968] master offset        -58 s2 freq  +37813 path delay     10878
Aug 21 14:35:07 bbb-dd03 ptp4l: [12855.968] master offset       -108 s2 freq  +37746 path delay     10877
`

I am measuring the difference between Time on Master and Slave1 on a period of 100 seconds, here is the result :
<img width="431" alt="Code_tFj1SCtvSV" src="https://user-images.githubusercontent.com/6323038/63442094-2b4b9900-c43b-11e9-8856-f1f5b50c6be1.png">

and here is the time difference between Slave 1 and Slave 2:

<img width="440" alt="Code_XlPXUAHiTR" src="https://user-images.githubusercontent.com/6323038/63442086-27b81200-c43b-11e9-9103-eddc74944068.png">

Very strange jittering and very high delay, nothing compared to the sub-microsecond in the article, any idea what I missed?

Thanks,

**Comment by volgy** [comment]
Hi,

The python test program (`test_timesync.py`) is a very coarse-grained (inaccurate) test for the timing accuracy on the nodes. If you look at the source code, you can see that it uses the built-in python `sleep()` logic for periodic wake-ups. Also, the time values on the output are measured in the nodes' own system clock, thus cannot be used to estimate the timing accuracy between nodes. I guess, the name of the script is a misnomer, since it really measures the timing accuracy of the `sleep()` blocking python call.

You need to instrument (GPIO pins) the nodes  and use `tools/sync_gen` to measure the relative timing accuracy of the nodes.
